ITEMS = [
 {"item": "Audifonos", "image": "/src/utils/assets/images/audifonos.png"},
 {"item": "Bicicleta", "image": "/src/utils/assets/images/bici.png"},
 {"item": "Botella termica", "image": "/src/utils/assets/images/botella_terminca.png"},
 {"item": "Cepillo de dientes", "image": "/src/utils/assets/images/cepillo_de_dientes.png"},
 {"item": "Cuaderno", "image": "/src/utils/assets/images/libreta.png"},
 {"item": "Hervidor", "image": "/src/utils/assets/images/hervidor.png"},
 {"item": "Lamparas", "image": "/src/utils/assets/images/lampara.jpg"},
 {"item": "Lapiz", "image": "/src/utils/assets/images/lapiz.png"},
 {"item": "Lentes", "image": "/src/utils/assets/images/lentes.png"},
 {"item": "Microondas", "image": "/src/utils/assets/images/microondas.png"},
 {"item": "Platos", "image": "/src/utils/assets/images/plato.png"},
 {"item": "Tazas", "image": "/src/utils/assets/images/taza.png"},
 {"item": "Silla", "image": "/src/utils/assets/images/silla.png"},
 {"item": "Cubiertos", "image": "/src/utils/assets/images/cubiertos.png"},
 {"item": "Tupper", "image": "/src/utils/assets/images/tupper.png"},
]

MATERIALS = [
 {"type": "Grafeno",
  "material": "Grafito",
  "carbon_footprint": 9.15,
  "hydric_footprint": 112.0,
  "diesel_consumption": 0.01,
  "co2_kg": 0.06124,
  "diesel_kg": 0.02294,
  "exporter": "China"},
 {"type": "Metales",
  "material": "Aluminio",
  "carbon_footprint": 2.502,
  "hydric_footprint": 147.12,
  "diesel_consumption": 0.7189,
  "co2_kg": 0.05106,
  "diesel_kg": 0.01912,
  "exporter": "China"},
 {"type": "Metales",
  "material": "Cobre",
  "carbon_footprint": 0.879,
  "hydric_footprint": 222.6,
  "diesel_consumption": 0.2686,
  "co2_kg": 0.00731,
  "diesel_kg": 0.00274,
  "exporter": "China"},
 {"type": "Metales",
  "material": "Acero",
  "carbon_footprint": 3.51,
  "hydric_footprint": 40.2,
  "diesel_consumption": 1.075,
  "co2_kg": 0.01755,
  "diesel_kg": 0.00657,
  "exporter": "China"},
 {"type": "Metales",
  "material": "Niquel",
  "carbon_footprint": 9.565,
  "hydric_footprint": 250.0,
  "diesel_consumption": 3.1689,
  "co2_kg": 0.0031,
  "diesel_kg": 0.00116,
  "exporter": "China"},
 {"type": "Metales",
  "material": "Titanio",
  "carbon_footprint": 14.741,
  "hydric_footprint": 140.0,
  "diesel_consumption": 4.3096,
  "co2_kg": 0.00778,
  "diesel_kg": 0.00291,
  "exporter": "China"},
 {"type": "Metales",
  "material": "Acero inoxidable",
  "carbon_footprint": 0.492,
  "hydric_footprint": 24.2,
  "diesel_consumption": 0.03,
  "co2_kg": 0.00477,
  "diesel_kg": 0.00179,
  "exporter": "China"},
 {"type": "Metales",
  "material": "Hierro",
  "carbon_footprint": 1.138,
  "hydric_footprint": 40.0,
  "diesel_consumption": 0.5543,
  "co2_kg": 0.00349,
  "diesel_kg": 0.00131,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Vidrio",
  "carbon_footprint": 1.603,
  "hydric_footprint": 99.05,
  "diesel_consumption": 0.5089,
  "co2_kg": 0.00631,
  "diesel_kg": 0.00236,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Madera",
  "carbon_footprint": 0.051,
  "hydric_footprint": 0.42,
  "diesel_consumption": 0.0169,
  "co2_kg": 0.05566,
  "diesel_kg": 0.02084,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Tinta",
  "carbon_footprint": 4.546,
  "hydric_footprint": 30.0,
  "diesel_consumption": 0.004,
  "co2_kg": 0.05398,
  "diesel_kg": 0.02022,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Arcilla",
  "carbon_footprint": 0.019,
  "hydric_footprint": 350.0,
  "diesel_consumption": 0.01,
  "co2_kg": 0.01406,
  "diesel_kg": 0.00526,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Celuloide",
  "carbon_footprint": 0.849,
  "hydric_footprint": 2481.61,
  "diesel_consumption": 0.265,
  "co2_kg": 0.03163,
  "diesel_kg": 0.01185,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Carton",
  "carbon_footprint": 0.704,
  "hydric_footprint": 61.1,
  "diesel_consumption": 0.0038,
  "co2_kg": 0.18373,
  "diesel_kg": 0.06881,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Vidrio templado",
  "carbon_footprint": 0.971,
  "hydric_footprint": 11.4,
  "diesel_consumption": 0.0011,
  "co2_kg": 0.052,
  "diesel_kg": 0.01948,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Porcelana",
  "carbon_footprint": 0.428,
  "hydric_footprint": 204.0,
  "diesel_consumption": 0.004,
  "co2_kg": 0.05742,
  "diesel_kg": 0.0215,
  "exporter": "China"},
 {"type": "No metalicos",
  "material": "Madera contrachapada",
  "carbon_footprint": 1.86,
  "hydric_footprint": 15.0,
  "diesel_consumption": 0.006,
  "co2_kg": 0.3445,
  "diesel_kg": 0.12903,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Nylon",
  "carbon_footprint": 7.715,
  "hydric_footprint": 8917.86,
  "diesel_consumption": 2.5657,
  "co2_kg": 0.03244,
  "diesel_kg": 0.01215,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "PVC",
  "carbon_footprint": 1.751,
  "hydric_footprint": 57.05,
  "diesel_consumption": 1.0121,
  "co2_kg": 0.01611,
  "diesel_kg": 0.00603,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Acrilico (pmma)",
  "carbon_footprint": 7.62,
  "hydric_footprint": 58.87,
  "diesel_consumption": 3.1016,
  "co2_kg": 0.04536,
  "diesel_kg": 0.01699,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Polietileno de baja densidad (pebd)",
  "carbon_footprint": 13.904,
  "hydric_footprint": 41.57,
  "diesel_consumption": 7.4991,
  "co2_kg": 0.04208,
  "diesel_kg": 0.01576,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Polipropileno",
  "carbon_footprint": 3.799,
  "hydric_footprint": 650.87,
  "diesel_consumption": 2.1431,
  "co2_kg": 0.04395,
  "diesel_kg": 0.01646,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "ABS",
  "carbon_footprint": 4.155,
  "hydric_footprint": 100.0,
  "diesel_consumption": 2.3443,
  "co2_kg": 0.03873,
  "diesel_kg": 0.0145,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Policarbonato",
  "carbon_footprint": 8.55,
  "hydric_footprint": 160.0,
  "diesel_consumption": 2.6513,
  "co2_kg": 0.00886,
  "diesel_kg": 0.00332,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "TR-90",
  "carbon_footprint": 7.715,
  "hydric_footprint": 8917.86,
  "diesel_consumption": 2.5657,
  "co2_kg": 0.1378,
  "diesel_kg": 0.05161,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Optyl",
  "carbon_footprint": 3.254,
  "hydric_footprint": 35.42,
  "diesel_consumption": 0.004,
  "co2_kg": 0.03086,
  "diesel_kg": 0.01156,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Poliuretano",
  "carbon_footprint": 177.42,
  "hydric_footprint": 65.65,
  "diesel_consumption": 0.005,
  "co2_kg": 0.14541,
  "diesel_kg": 0.05446,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Polietileno de alta densidad (hdpe)",
  "carbon_footprint": 2.109,
  "hydric_footprint": 44.22,
  "diesel_consumption": 1.8161,
  "co2_kg": 0.01581,
  "diesel_kg": 0.00592,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "PET (tereftalato de polietileno)",
  "carbon_footprint": 4.597,
  "hydric_footprint": 161.84,
  "diesel_consumption": 2.5763,
  "co2_kg": 0.12304,
  "diesel_kg": 0.04608,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Gomas (latex)",
  "carbon_footprint": 0.13,
  "hydric_footprint": 62.4,
  "diesel_consumption": 0.005,
  "co2_kg": 0.01455,
  "diesel_kg": 0.00545,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Caucho",
  "carbon_footprint": 3.24,
  "hydric_footprint": 3250.0,
  "diesel_consumption": 0.02,
  "co2_kg": 0.11798,
  "diesel_kg": 0.04419,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Silicona",
  "carbon_footprint": 4.754,
  "hydric_footprint": 200.0,
  "diesel_consumption": 1.7717,
  "co2_kg": 0.05997,
  "diesel_kg": 0.02246,
  "exporter": "China"},
 {"type": "Polimeros",
  "material": "Espuma de poliuretano",
  "carbon_footprint": 0.935,
  "hydric_footprint": 28.2,
  "diesel_consumption": 0.003,
  "co2_kg": 0.033,
  "diesel_kg": 0.01236,
  "exporter": "China"},
 {"type": "Sinteticos",
  "material": "Fibra de carbono",
  "carbon_footprint": 87.82,
  "hydric_footprint": 30.0,
  "diesel_consumption": 0.004,
  "co2_kg": 0.01217,
  "diesel_kg": 0.00456,
  "exporter": "China"},
 {"type": "Sinteticos",
  "material": "Fibra de vidrio",
  "carbon_footprint": 1.385,
  "hydric_footprint": 396.34,
  "diesel_consumption": 0.5133,
  "co2_kg": 0.03084,
  "diesel_kg": 0.01155,
  "exporter": "China"},
 {"type": "Sinteticos",
  "material": "Vinilo",
  "carbon_footprint": 2.294,
  "hydric_footprint": 1332.63,
  "diesel_consumption": 1.1272,
  "co2_kg": 0.05648,
  "diesel_kg": 0.02115,
  "exporter": "China"},
 {"type": "Textiles",
  "material": "Lana",
  "carbon_footprint": 17.5,
  "hydric_footprint": 38540.0,
  "diesel_consumption": 0.03,
  "co2_kg": 0.30556,
  "diesel_kg": 0.11444,
  "exporter": "China"},
 {"type": "Textiles",
  "material": "Algodon",
  "carbon_footprint": 0.88,
  "hydric_footprint": 18000.0,
  "diesel_consumption": 0.05,
  "co2_kg": 0.45934,
  "diesel_kg": 0.17204,
  "exporter": "China"},
 {"type": "Textiles",
  "material": "Lino",
  "carbon_footprint": 1.38,
  "hydric_footprint": 2500.0,
  "diesel_consumption": 0.04,
  "co2_kg": 0.03936,
  "diesel_kg": 0.01474,
  "exporter": "China"},
 {"type": "Textiles",
  "material": "Cuero sintetico",
  "carbon_footprint": 4.756,
  "hydric_footprint": 70.0,
  "diesel_consumption": 0.003,
  "co2_kg": 0.08994,
  "diesel_kg": 0.03369,
  "exporter": "China"}
]

ITEM_MATERIALS = {
    "Audifonos": {
        "fixed": ["Aluminio", "Cobre", "ABS"],
        "variable": ["Espuma de poliuretano", "Cuero sintetico", "Gomas (latex)"]
    },
    "Bicicleta": {
        "fixed": ["Nylon", "Caucho", "Gomas (latex)", "Espuma de poliuretano"],
        "variable": ["Aluminio", "Acero", "Fibra de carbono", "Titanio", "Nylon"]
    },
    "Botella termica": {
        "fixed": ["Silicona", "Gomas (latex)", "Polietileno de alta densidad (hdpe)"],
        "variable": ["Acero", "Aluminio", "Cobre", "Vidrio", "PET (tereftalato de polietileno)"]
    },
    "Cepillo de dientes": {
        "fixed": ["Nylon"],
        "variable": ["PVC", "Acrilico (pmma)", "Gomas (latex)"]
    },
    "Cuaderno": {
        "fixed": ["Celuloide"],
        "variable": ["Carton", "Cuero sintetico", "Polietileno de baja densidad (pebd)"]
    },
    "Hervidor": {
        "fixed": ["Cobre", "Silicona"],
        "variable": ["Polipropileno", "ABS", "Acero inoxidable", "Aluminio", "Acrilico (pmma)", "Vidrio"]
    },
    "Lamparas": {
        "fixed": ["Cobre", "Acero", "Hierro", "Aluminio", "Cobre", "ABS", "PVC", "Madera"],
        "variable": ["Acrilico (pmma)", "Vidrio", "Algodon", "Lino"],
    },
    "Lapiz": {
        "fixed": [],
        "variable": ["Aluminio", "Acero inoxidable", "Polipropileno", "Polietileno de alta densidad (hdpe)", "Policarbonato", "PVC", "Madera", "Tinta", "Grafito", "Arcilla", "Silicona", "Caucho"]
    },
    "Lentes": {
        "fixed": ["Silicona", "Caucho"],
        "variable": ["Acero inoxidable", "Titanio", "Aluminio", "Nylon", "TR-90", "Policarbonato", "Optyl"]
    },
    "Microondas": {
        "fixed": ["Nylon", "Vidrio templado"],
        "variable": ["Acero inoxidable", "Polipropileno"]
    },
    "Platos": {
        "fixed": [],
        "variable": ["Polipropileno", "ABS", "Vidrio", "Vidrio templado", "Arcilla", "Madera", "Celuloide", "Aluminio", "Acero inoxidable"]
    },
    "Tazas": {
        "fixed": [],
        "variable": ["Porcelana", "Arcilla", "Vidrio templado", "Vidrio", "Madera", "Acero inoxidable", "Polipropileno", "ABS"]
    },
    "Silla": {
        "fixed": [],
        "variable": ["Acero inoxidable", "Aluminio", "Madera contrachapada", "Nylon", "Polipropileno", "Fibra de vidrio", "Poliuretano", "Cuero sintetico", "Vinilo", "Silicona", "Gomas (latex)", "Espuma de poliuretano", "Caucho"]
    },
    "Cubiertos": {
        "fixed": [],
        "variable": ["Acero inoxidable", "Polipropileno", "Madera", "Aluminio", "Cobre", "Silicona"]
    },
    "Tupper": {
        "fixed": [],
        "variable": ["Polipropileno", "Polietileno de alta densidad (hdpe)", "Policarbonato", "Acero inoxidable", "Gomas (latex)", "Silicona"]
    }
}

